codecov:
  branch: azuedev
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "/gh/madhukargilla/cloudbridge/cloudbridge/cloud/providers/aws"  # ignore folders and all its contents

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

