ARG EXTRA=full
ARG PYTHON=latest
FROM python:$PYTHON

RUN apt-get update \
 && apt-get --force-yes install -y curl vim git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN pip install --no-cache-dir pep8 flake8 pyflakes pyyaml ipython cloudbridge[$EXTRA]

COPY scripts/ cloudbridge_scripts/
